"""set message state default

Revision ID: d8a732491cab
Revises: 28dbf78cf56c
Create Date: 2022-05-28 10:41:09.741515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a732491cab'
down_revision = '28dbf78cf56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
